Better error handling. This is so that the error status of the last command gets reported back.

diff --git a/update-svn-git b/update-svn-git
--- a/update-svn-git
+++ b/update-svn-git
@@ -1,27 +1,28 @@
-#!/bin/bash -e
+#!/bin/bash
+
+# Exit if any of the commands fails.
+set -e 
 
 cd $HOME/repos/mirror
 lockfile=.`basename $0`.lock
 
 if ( set -o noclobber; echo "$$" > "$lockfile") 2> /dev/null; 
 then
-   trap 'rm -f "$lockfile"; exit $?' INT TERM EXIT
+   trap 'stat=$?; rm -f "$lockfile"; exit $stat' EXIT
    find . -mindepth 1 -maxdepth 2 -type d -name \*.git-svn | while read dir
    do
 	   pushd $dir 
-	   git svn fetch -q || exit 1
+	   git svn fetch -q 
 	   popd 
    done
 
    find . -mindepth 1 -maxdepth 2 -type d -name \*?.git| while read dir
    do
 	   pushd $dir 
-	   git fetch -q || exit 1
-	   git --bare update-server-info
+	   git fetch -q
+	   git --bare update-server-info || exit 1
 	   popd 
    done
-   rm -f "$lockfile"
-   trap - INT TERM EXIT
 else
    echo "Failed to acquire lockfile: $lockfile" 
    echo "Held by PID: $(cat $lockfile)"
